[workspace]

members = [
  "lib",
  "ead",
  "ead/edhoc-ead-none",
  "ead/edhoc-ead-zeroconf",
  "crypto",
  "crypto/edhoc-crypto-cc2538",
  "crypto/edhoc-crypto-hacspec",
  "crypto/edhoc-crypto-psa",
  "crypto/edhoc-crypto-cryptocell310-sys",
  "crypto/edhoc-crypto-mbedtls",
  "examples/coap",
  "examples/edhoc-rs-no_std",
  "examples/edhoc-rs-cc2538",
]

# reduced "default-members", should include only packages that can be built and
# tested on the host architecture
default-members = [
  "lib",
  "ead",
  "crypto",
  "crypto/edhoc-crypto-hacspec",
  "examples/coap",
]

# according to https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html,
# this needs to be explicitly set if using virtual manifests (like this).
# We need this so dependency crates use it *in all cases*.
# Specifically, `psa-crypto` merges build-dependency and regular dependency
# features without this, causing forced "std" in downstream crate.
resolver = "2"

[patch.crates-io]
hacspec-lib = { git = "https://github.com/malishav/hacspec", branch = "aesccm" }
hacspec-p256 = { git = "https://github.com/malishav/hacspec", branch = "aesccm" }
hacspec-hkdf = { git = "https://github.com/malishav/hacspec", branch = "aesccm" }
hacspec-sha256 = { git = "https://github.com/malishav/hacspec", branch = "aesccm" }
hacspec-aes = { git = "https://github.com/malishav/hacspec", branch = "aesccm" }
hacspec-aes-ccm = { git = "https://github.com/malishav/hacspec", branch = "aesccm" }
psa-crypto = { git = "https://github.com/malishav/rust-psa-crypto", branch = "baremetal" }
