name: Rust

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install thumbv7m-none-eabi rust target support
      run: rustup target add thumbv7m-none-eabi
    - name: Build no_std edhoc-rs
      run: cargo build --target="thumbv7m-none-eabi" --features="hacspec-cc2538" --no-default-features --package edhoc-rs
    - name: Build examples/edhoc-rs-no_std cc2538
      run: cd examples/edhoc-rs-no_std && cargo build
    - name: Build examples/edhoc-rs-no_std psa
      run: cd examples/edhoc-rs-no_std && cargo build --no-default-features --features=psa
